import Config

# Federation: store node identity in a local dev-friendly path
config :platform, :node_identity_path, "priv/dev/node_identity.json"

bind_ip =
  case System.get_env("PHX_BIND_IP", "127.0.0.1") do
    "0.0.0.0" -> {0, 0, 0, 0}
    _ -> {127, 0, 0, 1}
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :platform, PlatformWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Set PHX_BIND_IP=0.0.0.0 to allow access from other machines/containers.
  http: [ip: bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cXCcOi6k6TJhaXvpDaJg01ag2Fzt2q7x+NEfL+bVIZuB605DfGXXT/yylE3JAOax",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:platform, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:platform, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :platform, PlatformWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/platform_web/router\.ex$"E,
      ~r"lib/platform_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Default Repo config for local dev. Matches the `postgres` role created
# in CONTRIBUTING.md setup. `runtime.exs` overrides this with DATABASE_URL
# when set, so you can point at a different instance without editing this
# file.
config :platform, Platform.Repo,
  username: System.get_env("PGUSER", "postgres"),
  password: System.get_env("PGPASSWORD", "postgres"),
  hostname: System.get_env("PGHOST", "localhost"),
  port: String.to_integer(System.get_env("PGPORT", "5432")),
  database: System.get_env("PLATFORM_DEV_DATABASE", "platform_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Enable dev routes for dashboard and mailbox
config :platform, dev_routes: true

# Dev machines don't need to pre-provision /data/platform/chat_uploads.
# The upload path falls back to a tmp dir via AttachmentStorage.storage_root/0.
config :platform,
  skip_attachment_storage_check: true,
  attachment_signing_key: "dev-attachment-signing-key-do-not-use-in-prod"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
