defmodule PlatformWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :platform

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_platform_session",
    signing_salt: "LVkhtRt/",
    same_site: "Lax",
    http_only: true
  ]

  socket "/runtime/ws", PlatformWeb.RuntimeSocket,
    websocket: [timeout: 120_000, check_origin: false],
    longpoll: false

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :platform,
    gzip: not code_reloading?,
    only: PlatformWeb.static_paths(),
    raise_on_missing_only: code_reloading?
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
  end

  plug(Plug.RequestId)
  plug(PlatformWeb.Plugs.RewriteRemoteIp)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {PlatformWeb.Plugs.CacheBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(PlatformWeb.Router)
end
